const LOCK_TYPES = {
  FETCH: '[LOCK] FETCH',
  SUCCESS: '[LOCK] SUCCESS',
  ERROR: '[LOCK] ERROR',
  UNLOCK: 'UNLOCK',
  UNLOCK_SUCCESS: 'UNLOCK_SUCCESS',
  UNLOCK_ERROR: 'UNLOCK_ERROR'
}

export default LOCK_TYPES
